create table item
(
    id        int auto_increment
        primary key,
    name      varchar(100) not null,
    blueprint varchar(256) not null,
    icon      varchar(256) not null,
    price     int          not null,
    price_bp  int          not null,
    category  varchar(100) not null
);

INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (1, 'longneck', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponOneShotRifle.PrimalItem_WeaponOneShotRifle\'', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/a/a2/Longneck_Rifle.png/revision/latest?cb=20150615120857', 1000, 5000, 'WEAPON');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (2, 'tek_rifle', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_TekRifle.PrimalItem_TekRifle\'', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/d/d4/Tek_Rifle.png/revision/latest?cb=20170131150615', 2000, 10000, 'WEAPON');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (3, 'pump_action_shotgun', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponMachinedShotgun.PrimalItem_WeaponMachinedShotgun\'', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/a/a9/Pump-Action_Shotgun.png/revision/latest?cb=20150722135003', 1000, 5000, 'WEAPON');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (4, 'crossbow', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponCrossbow.PrimalItem_WeaponCrossbow\'', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/7/79/Crossbow.png/revision/latest?cb=20150722135106', 1000, 5000, 'WEAPON');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (5, 'sword', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponSword.PrimalItem_WeaponSword\'', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/8/89/Sword.png/revision/latest?cb=20151107061415', 1000, 5000, 'WEAPON');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (6, 'pike', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponPike.PrimalItem_WeaponPike\'', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/3/31/Pike.png/revision/latest?cb=20150615120808', 1000, 5000, 'WEAPON');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (7, 'chainsaw', 'Blueprint\'/Game/ScorchedEarth/WeaponChainsaw/PrimalItem_ChainSaw.PrimalItem_ChainSaw\'', 'https://ark.wiki.gg/images/c/cc/Chainsaw.png?format=original', 1000, 5000, 'WEAPON');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (8, 'compound_bow', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponCompoundBow.PrimalItem_WeaponCompoundBow\'', 'https://ark.wiki.gg/images/9/9e/Compound_Bow.png?format=original', 1000, 5000, 'WEAPON');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (9, 'harpoon_launcher', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponHarpoon.PrimalItem_WeaponHarpoon\'', 'https://ark.wiki.gg/images/e/ec/Harpoon_Launcher.png?format=original', 1000, 5000, 'WEAPON');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (10, 'simple_pistol', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponGun.PrimalItem_WeaponGun\'', 'https://ark.wiki.gg/images/d/d0/Simple_Pistol.png?format=original', 1000, 2500, 'WEAPON');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (11, 'shotgun', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponShotgun.PrimalItem_WeaponShotgun\'', 'https://ark.wiki.gg/images/6/61/Shotgun.png?format=original', 1000, 2500, 'WEAPON');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (12, 'fabricated_pistol', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponMachinedPistol.PrimalItem_WeaponMachinedPistol\'', 'https://ark.wiki.gg/images/2/2e/Fabricated_Pistol.png?format=original', 1000, 5000, 'WEAPON');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (13, 'assault_rifle', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponRifle.PrimalItem_WeaponRifle\'', 'https://ark.wiki.gg/images/e/e0/Assault_Rifle.png?format=original', 1000, 5000, 'WEAPON');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (14, 'fabricated_sniper_rifle', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponMachinedSniper.PrimalItem_WeaponMachinedSniper\'', 'https://ark.wiki.gg/images/9/9e/Fabricated_Sniper_Rifle.png?format=original', 1000, 5000, 'WEAPON');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (15, 'flamethrower', 'Blueprint\'/Game/ScorchedEarth/WeaponFlamethrower/PrimalItem_WeapFlamethrower.PrimalItem_WeapFlamethrower\'', 'https://ark.wiki.gg/images/a/ad/Flamethrower.png?format=original', 1000, 5000, 'WEAPON');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (16, 'tek_railgun', 'Blueprint\'/Game/Aberration/WeaponTekSniper/PrimalItem_TekSniper.PrimalItem_TekSniper\'', 'https://ark.wiki.gg/images/e/eb/Tek_Railgun.png?format=original', 2000, 10000, 'WEAPON');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (17, 'flak_helmet', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Metal/PrimalItemArmor_MetalHelmet.PrimalItemArmor_MetalHelmet\'', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/e/ec/Flak_Helmet.png/revision/latest?cb=20150614181045', 1000, 2500, 'ARMOR');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (18, 'flak_chestpiece', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Metal/PrimalItemArmor_MetalShirt.PrimalItemArmor_MetalShirt\'', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/b/bf/Flak_Chestpiece.png/revision/latest?cb=20220414043038', 1000, 2500, 'ARMOR');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (19, 'flak_leggings', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Metal/PrimalItemArmor_MetalPants.PrimalItemArmor_MetalPants\'', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/0/07/Flak_Leggings.png/revision/latest?cb=20150614180958', 1000, 2500, 'ARMOR');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (20, 'flak_boots', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Metal/PrimalItemArmor_MetalBoots.PrimalItemArmor_MetalBoots\'', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/7/77/Flak_Boots.png/revision/latest?cb=20150614181106', 1000, 2500, 'ARMOR');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (21, 'flak_gauntlets', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Metal/PrimalItemArmor_MetalGloves.PrimalItemArmor_MetalGloves\'', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/f/f2/Flak_Gauntlets.png/revision/latest?cb=20150614181142', 1000, 2500, 'ARMOR');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (22, 'hazard_suit_helmet', 'Blueprint\'/Game/Aberration/CoreBlueprints/Items/Armor/HazardSuit/PrimalItemArmor_HazardSuitHelmet.PrimalItemArmor_HazardSuitHelmet\'', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/7/75/Hazard_Suit_Hat_%28Aberration%29.png/revision/latest?cb=20171212224559', 1000, 3000, 'ARMOR');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (23, 'hazard_suit_shirt', 'Blueprint\'/Game/Aberration/CoreBlueprints/Items/Armor/HazardSuit/PrimalItemArmor_HazardSuitShirt.PrimalItemArmor_HazardSuitShirt\'', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/9/92/Hazard_Suit_Shirt_%28Aberration%29.png/revision/latest?cb=20171212224603', 1000, 3000, 'ARMOR');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (24, 'hazard_suit_pants', 'Blueprint\'/Game/Aberration/CoreBlueprints/Items/Armor/HazardSuit/PrimalItemArmor_HazardSuitPants.PrimalItemArmor_HazardSuitPants\'', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/d/d0/Hazard_Suit_Pants_%28Aberration%29.png/revision/latest?cb=20171212224601', 1000, 3000, 'ARMOR');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (25, 'hazard_suit_boots', 'Blueprint\'/Game/Aberration/CoreBlueprints/Items/Armor/HazardSuit/PrimalItemArmor_HazardSuitBoots.PrimalItemArmor_HazardSuitBoots\'', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/6/67/Hazard_Suit_Boots_%28Aberration%29.png/revision/latest?cb=20171212224556', 1000, 3000, 'ARMOR');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (26, 'hazard_suit_gloves', 'Blueprint\'/Game/Aberration/CoreBlueprints/Items/Armor/HazardSuit/PrimalItemArmor_HazardSuitGloves.PrimalItemArmor_HazardSuitGloves\'', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/1/18/Hazard_Suit_Gloves_%28Aberration%29.png/revision/latest?cb=20171212224557', 1000, 3000, 'ARMOR');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (27, 'tek_helmet', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Tek/PrimalItemArmor_TekHelmet.PrimalItemArmor_TekHelmet\'', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/2/2e/Tek_Helmet.png/revision/latest?cb=20160502131658', 5000, 10000, 'ARMOR');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (28, 'tek_chestpiece', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Tek/PrimalItemArmor_TekShirt.PrimalItemArmor_TekShirt\'', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/2/21/Tek_Chestpiece.png/revision/latest?cb=20160502133132', 5000, 10000, 'ARMOR');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (29, 'tek_leggings', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Tek/PrimalItemArmor_TekPants.PrimalItemArmor_TekPants\'', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/0/0d/Tek_Leggings.png/revision/latest?cb=20160502132346', 5000, 10000, 'ARMOR');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (30, 'tek_boots', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Tek/PrimalItemArmor_TekBoots.PrimalItemArmor_TekBoots\'', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/1/1b/Tek_Boots.png/revision/latest?cb=20160502132606', 5000, 10000, 'ARMOR');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (31, 'tek_gauntlets', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Tek/PrimalItemArmor_TekGloves.PrimalItemArmor_TekGloves\'', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/2/21/Tek_Gauntlets.png/revision/latest?cb=20160502131937', 5000, 10000, 'ARMOR');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (32, 'riot_helmet', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Riot/PrimalItemArmor_RiotHelmet.PrimalItemArmor_RiotHelmet\'', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/3/3a/Riot_Helmet.png/revision/latest?cb=20160131043710', 2000, 5000, 'ARMOR');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (33, 'riot_chestpiece', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Riot/PrimalItemArmor_RiotShirt.PrimalItemArmor_RiotShirt\'', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/5/5a/Riot_Chestpiece.png/revision/latest?cb=20160131043651', 2000, 5000, 'ARMOR');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (34, 'riot_leggings', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Riot/PrimalItemArmor_RiotPants.PrimalItemArmor_RiotPants\'', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/a/ab/Riot_Leggings.png/revision/latest?cb=20160131043739', 2000, 5000, 'ARMOR');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (35, 'riot_boots', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Riot/PrimalItemArmor_RiotBoots.PrimalItemArmor_RiotBoots\'', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/5/5a/Riot_Boots.png/revision/latest?cb=20160131043756', 2000, 5000, 'ARMOR');
INSERT INTO dinos.item (id, name, blueprint, icon, price, price_bp, category) VALUES (36, 'riot_gauntlets', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Riot/PrimalItemArmor_RiotGloves.PrimalItemArmor_RiotGloves\'', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/d/d1/Riot_Gauntlets.png/revision/latest?cb=20160131043725', 2000, 5000, 'ARMOR');
