create table resource
(
    id          int auto_increment
        primary key,
    name        varchar(128) not null,
    icon        varchar(256) not null,
    quantity    int          not null,
    price       int          not null,
    msg_id      varchar(256) null,
    resource_id varchar(256) null,
    blueprint   varchar(256) null
);

INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (1, 'Wood', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/d/df/Wood.png/revision/latest?cb=20150615130549', 10000, 1000, '', 'WOOD', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Wood.PrimalItemResource_Wood\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (2, 'Fungal Wood', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/d/dc/Fungal_Wood_%28Aberration%29.png/revision/latest?cb=20171212224548', 10000, 1000, '', 'FUNGAL_WOOD', 'Blueprint\'/Game/Aberration/CoreBlueprints/Resources/PrimalItemResource_FungalWood.PrimalItemResource_FungalWood\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (3, 'Stone', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/d/d4/Stone.png/revision/latest?cb=20150615120930', 10000, 1000, '', 'STONE', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Stone.PrimalItemResource_Stone\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (4, 'Flint', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/2/2e/Flint.png/revision/latest?cb=20150615101007', 10000, 1000, '', 'FLINT', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Flint.PrimalItemResource_Flint\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (5, 'Pelt', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/4/45/Pelt.png/revision/latest?cb=20150929052115', 10000, 1000, '', 'PELT', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Pelt.PrimalItemResource_Pelt\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (6, 'Wool', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/3/34/Wool.png/revision/latest?cb=20170131144137', 10000, 1000, '', 'WOOL', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Wool.PrimalItemResource_Wool\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (7, 'Fiber', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/4/45/Fiber.png/revision/latest?cb=20200518133132', 10000, 1000, '', 'FIBER', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Fibers.PrimalItemResource_Fibers\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (8, 'Thatch', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/5/51/Thatch.png/revision/latest?cb=20150615130514', 10000, 1000, '', 'THATCH', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Thatch.PrimalItemResource_Thatch\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (9, 'Hide', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/9/96/Hide.png/revision/latest?cb=20150615102457', 10000, 1000, '', 'HIDE', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Hide.PrimalItemResource_Hide\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (10, 'Chitin', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/a/a1/Chitin.png/revision/latest?cb=20150614180439', 10000, 1000, '', 'CHITIN', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Chitin.PrimalItemResource_Chitin\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (11, 'Keratin', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/8/88/Keratin.png/revision/latest?cb=20150615103229', 10000, 1000, '', 'KERATIN', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Keratin.PrimalItemResource_Keratin\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (12, 'Shell Fragment', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/8/87/Shell_Fragment_%28Genesis_Part_1%29.png/revision/latest?cb=20200226174540', 10000, 1000, '', 'SHELL_FRAGMENT', 'Blueprint\'/Game/Genesis/Items/Resources/PrimalItemResource_ShellFragment.PrimalItemResource_ShellFragment\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (13, 'Metal', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/e/e1/Metal.png/revision/latest?cb=20150615123338', 10000, 2000, '', 'METAL', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Metal.PrimalItemResource_Metal\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (14, 'Charcoal', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/4/4f/Charcoal.png/revision/latest?cb=20200807125159', 10000, 2000, '', 'CHARCOAL', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Charcoal.PrimalItemResource_Charcoal\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (15, 'Rare Flower', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/b/bb/Rare_Flower.png/revision/latest?cb=20150615130335', 10000, 2000, '', 'RARE_FLOWER', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_RareFlower.PrimalItemResource_RareFlower\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (16, 'Rare Mushroom', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/3/30/Rare_Mushroom.png/revision/latest?cb=20150615130350', 10000, 2000, '', 'RARE_MUSHROOM', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_RareMushroom.PrimalItemResource_RareMushroom\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (17, 'Silk', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/7/7c/Silk_%28Scorched_Earth%29.png/revision/latest?cb=20160901230603', 10000, 2000, '', 'SILK', 'Blueprint\'/Game/ScorchedEarth/CoreBlueprints/Resources/PrimalItemResource_Silk.PrimalItemResource_Silk\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (18, 'Sap', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/7/73/Sap.png/revision/latest?cb=20160706145127', 10000, 2000, '', 'SAP', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Sap.PrimalItemResource_Sap\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (19, 'Oil', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/0/06/Oil.png/revision/latest?cb=20150615130100', 10000, 2000, '', 'OIL', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Oil.PrimalItemResource_Oil\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (20, 'Obsidian', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/2/23/Obsidian.png/revision/latest?cb=20150615125926', 10000, 2000, '', 'OBSIDIAN', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Obsidian.PrimalItemResource_Obsidian\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (21, 'Crystal', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/3/31/Crystal.png/revision/latest?cb=20150618193219', 10000, 2000, '', 'CRYSTAL', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Crystal.PrimalItemResource_Crystal\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (22, 'Silica Pearl', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/4/4a/Silica_Pearls.png/revision/latest?cb=20150615130449', 10000, 2000, '', 'SILICA_PEARL', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_SilicaPearls.PrimalItemResource_SilicaPearls\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (23, 'Polymer', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/8/81/Polymer.png/revision/latest?cb=20150615130200', 10000, 3000, '', 'POLYMER', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Polymer.PrimalItemResource_Polymer\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (24, 'Organic Polymer', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/1/13/Organic_Polymer.png/revision/latest?cb=20160424034337', 10000, 3000, '', 'ORGANIC_POLYMER', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_OrganicPolymer.PrimalItemResource_OrganicPolymer\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (25, 'Cementing Paste', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/0/03/Cementing_Paste.png/revision/latest?cb=20180801020251', 10000, 3000, '', 'CEMENTING_PASTE', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ChitinPaste.PrimalItemResource_ChitinPaste\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (26, 'Green Gem', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/c/c3/Green_Gem_%28Aberration%29.png/revision/latest?cb=20171212224555', 10000, 3000, '', 'GREEN_GEM', 'Blueprint\'/Game/Aberration/CoreBlueprints/Resources/PrimalItemResource_Gem_Fertile.PrimalItemResource_Gem_Fertile\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (27, 'Blue Gem', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/1/13/Blue_Gem_%28Aberration%29.png/revision/latest?cb=20171212224538', 10000, 3000, '', 'BLUE_GEM', 'Blueprint\'/Game/Aberration/CoreBlueprints/Resources/PrimalItemResource_Gem_Precious.PrimalItemResource_Gem_Precious\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (28, 'Red Gem', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/a/a6/Red_Gem_%28Aberration%29.png/revision/latest?cb=20171212224551', 10000, 3000, '', 'RED_GEM', 'Blueprint\'/Game/Aberration/CoreBlueprints/Resources/PrimalItemResource_Gem_Radiant.PrimalItemResource_Gem_Radiant\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (29, 'Congealed Gas Ball', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/7/7e/Congealed_Gas_Ball_%28Aberration%29.png/revision/latest?cb=20171212224544', 10000, 3000, '', 'CONGEALED_GAS_BALL', 'Blueprint\'/Game/Aberration/CoreBlueprints/Resources/PrimalItemResource_GasBalls.PrimalItemResource_GasBalls\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (30, 'Giant Bee Honey', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/a/a5/Giant_Bee_Honey.png/revision/latest?cb=20170507225653', 10000, 3000, '', 'GIANT_BEE_HONEY', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Honey.PrimalItemResource_Honey\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (31, 'Leech Blood', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/e/e3/Leech_Blood.png/revision/latest?cb=20160606192157', 10000, 3000, '', 'LEECH_BLOOD', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_LeechBlood.PrimalItemResource_LeechBlood\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (32, 'Bio Toxin', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/4/41/Bio_Toxin.png/revision/latest?cb=20180801015700', 10000, 5000, '', 'BIO_TOXIN', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_BioToxin.PrimalItemResource_BioToxin\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (33, 'Ammonite Bile', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/f/fd/Ammonite_Bile.png/revision/latest?cb=20170226224350', 1000, 1000, '', 'AMMONITE_BILE', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_AmmoniteBlood.PrimalItemResource_AmmoniteBlood\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (34, 'Black Pearl', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/4/4c/Black_Pearl.png/revision/latest?cb=20160410175730', 1000, 1000, '', 'BLACK_PEARL', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_BlackPearl.PrimalItemResource_BlackPearl\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (35, 'Achatina Paste', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/0/03/Cementing_Paste.png/revision/latest?cb=20180801020251', 1000, 1000, '1329516547936620634', 'ACHATINA_PASTE', 'Blueprint\'/Game/PrimalEarth/Dinos/Achatina/PrimalItemResource_SnailPaste.PrimalItemResource_SnailPaste\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (36, 'Angler Gel', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/7/75/AnglerGel.png/revision/latest?cb=20180801015710', 1000, 1000, '', 'ANGLER_GEL', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_AnglerGel.PrimalItemResource_AnglerGel\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (37, 'Deathworm Horn', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/3/34/Deathworm_Horn_%28Scorched_Earth%29.png/revision/latest?cb=20160901205512', 1000, 1000, '', 'DEATHWORM_HORN', 'Blueprint\'/Game/ScorchedEarth/CoreBlueprints/Resources/PrimalItemResource_DeathwormHorn.PrimalItemResource_DeathwormHorn\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (38, 'Woolly Rhino Horn', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/3/38/Woolly_Rhino_Horn.png/revision/latest?cb=20160410175521', 1000, 1000, '', 'WOOLLY_RHYNO_HORN', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Rhino_Horn.PrimalItemResource_Rhino_Horn\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (39, 'Element', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/4/4b/Element.png/revision/latest?cb=20150615125857', 1000, 1000, '', 'ELEMENT', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Element.PrimalItemResource_Element\'');
INSERT INTO dinos.resource (id, name, icon, quantity, price, msg_id, resource_id, blueprint) VALUES (40, 'Electronics', 'https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/d/dd/Electronics.png/revision/latest?cb=20150615100650', 10000, 3000, '', 'ELECTRONICS', 'Blueprint\'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Electronics.PrimalItemResource_Electronics\'');
